version: '3.8'

services:
  front:
    image: yadtamar/front:latest
    ports:
      - "5173:5173"
    depends_on:
      - back

  back:
    image: yadtamar/back:latest
    ports:
      - "8000:8000"
