version: "3.8"

services:
  front:
    image: yadtamar/front:latest
    ports:
      - "5173:5173"
    depends_on:
      - back
    environment:
      REACT_APP_BACKEND_URL: http://back:8000
    networks:
      - mynetwork

  back:
    image: yadtamar/back:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: mydatabase # שם הדאטהבייס, אם צריך
    networks:
      - mynetwork

  db:
    image: postgres:16.2
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mydatabase # שם הדאטהבייס
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
