version: "3.8"

services:
  front:
    image: yadtamar/front:latest
    ports:
      - "5173:5173"
    depends_on:
      - back
    environment:
      REACT_APP_BACKEND_URL: http://back:8000
    networks:
      - mynetwork

  back:
    image: yadtamar/back:latest
    ports:
      - "8000:8000"
    depends_on:
      - db # תלות ב-DB
    environment:
      DB_HOST: db # מפנה לשם ה-Service של ה-DB
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: mydatabase # שם הדאטהבייס, אם צריך
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME} #yad-tamar
      POSTGRES_PASSWORD: ${DB_PASSWORD} #kingshoval!123
      POSTGRES_DB: 20.50.143.29
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - mynetwork
        image: postgres:16.2

    ##############################################
    container_name: postgres-db
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
