services:
  front:
    image: yadtamar/front:latest
    ports:
      - "8080:5173"
    depends_on:
      - back
    environment:
      VITE_HOST_URL: http://back:8000
    networks:
      - mynetwork

  back:
    image: yadtamar/back:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_IP: db:5432
      POSTGRES_USER: yad-tamar
      POSTGRES_PASSWORD: kingshoval!123
      DB_NAME: yad-tamar
    networks:
      - mynetwork

  db:
    image: postgres:16.2
    container_name: postgres-db
    environment:
      POSTGRES_USER: yad-tamar
      POSTGRES_PASSWORD: kingshoval!123
      POSTGRES_DB: yad-tamar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
