version: '2'
services:
  db:
    image: postgres:16.2
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # front:
  #   image: yadtamar/front:latest
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - back
  # back:
  #   image: yadtamar/back:latest
  #   ports:
  #     - "8000:8000"
volumes:
  postgres_data:
