name: CI/CD for Full Deployment

on:
  push:
    branches:
      - workflow-compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull latest images
        run: |
          docker pull yadtamar/back:latest
          docker pull yadtamar/front:latest

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/user/project/
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker-compose logs -f

#
