name: CI/CD for Full Deployment

on:
  push:
    branches:
      - workflow-compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull latest images
        run: |
          docker pull yadtamar/back:latest
          docker pull yadtamar/front:latest

      - name: Copy docker-compose.yml to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ./docker/yad-tamar/docker-compose.yml
          target: /home/user-yad-tamar/folder
          debug: true

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/user-yad-tamar/folder/docker/yad-tamar/
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker-compose -f logs -f
