name: CI/CD for Full Deployment

on:
  push:
    branches:
      - workflow-compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.SSH_USER }} --password-stdin

      - name: Pull latest images
        run: |
          docker pull yadtamar/back:latest
          docker pull yadtamar/front:latest

      - name: Clean up disk space on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            df -h  # מציג את מצב האחסון לפני הניקוי
            sudo docker system prune -f  # מנקה קונטיינרים ותמונות ישנות
            sudo rm -rf /tmp/*  # מנקה קבצים זמניים
            df -h  # מציג את מצב האחסון אחרי הניקוי
          debug: true

      - name: Copy docker-compose.yml to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: docker/yad-tamar/docker-compose.yml
          target: ~/docker-compose.yml # נתיב מפורש לקובץ
          debug: true

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            ls -la  # בדיקה אם הקובץ הועתק
            cat ~/docker-compose.yml  # מציג את תוכן הקובץ כדי לוודא שהוא שם
            docker-compose -f ~/docker-compose.yml down  # משתמש בקובץ עם נתיב מפורש
            docker-compose -f ~/docker-compose.yml pull
            docker-compose -f ~/docker-compose.yml up -d
            docker-compose -f ~/docker-compose.yml logs -f
          debug: true
